name: build
on:
  push:
    # tags-ignore:
    #   - v*.**
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build
        run: go build -o apiMailSend-${{ matrix.goos }}-${{ matrix.goarch }} -trimpath -ldflags "-w -s" -v  
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: apiMailSend-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./apiMailSend-${{ matrix.goos }}-${{ matrix.goarch }}
      